### PR TITLE
Add port redirection

### PR DESCRIPTION
**Pull request by ivyleavedtoadflax**
Follows #21. Adds port redirect to the `remote connect` command.

To do this we probably need to do the following:

- [X] Use case when instead of if else for handling commands
- [ ] Use case when for handling flags
- [ ] Handle options, e.g.: `-r|--redirect localhost:8080:8080`

### CODE REVIEW

**Comment by ivyleavedtoadflax** [comment]
Might be easier to implement #14 rather than do this in bash...

**Comment by nsorros** [comment]
Hey @ivyleavedtoadflax, could we get this into remote? What was the rational behind using case, do we need case for port redirection or we should split the case feature to another PR and implement port redirection first.

This is relevant for both prodigy and tensor board

**Comment by ivyleavedtoadflax** [comment]
not sure...i had problems stacking options and flags, perhaps that is why i went for case

**Comment by ivyleavedtoadflax** [comment]
Please save me and take this over @nsorros

**Pull request closed without merging**
